# Generated by Django 2.2.12 on 2024-08-01 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fisat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laballotment',
            name='end_date',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='laballotment',
            name='start_date',
            field=models.CharField(max_length=100),
        ),
    ]
