# Generated by Django 4.2.14 on 2024-08-03 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fisat', '0002_auto_20240801_1027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laballotment',
            name='day_allotted',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
