# Generated by Django 4.2.14 on 2024-08-07 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fisat', '0003_alter_laballotment_day_allotted'),
    ]

    operations = [
        migrations.AddField(
            model_name='laballotment',
            name='external',
            field=models.CharField(default='external', max_length=10),
        ),
    ]
