# Generated by Django 4.2.14 on 2024-08-07 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fisat', '0004_laballotment_external'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laballotment',
            name='id',
            field=models.AutoField(db_column='id', primary_key=True, serialize=False),
        ),
    ]
