# Generated by Django 2.2.12 on 2025-04-11 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fisat', '0005_alter_laballotment_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('privilege', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'user_table',
            },
        ),
    ]
